// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.3
// source: internal/message/proto/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertMessageRequest) Reset() {
	*x = InsertMessageRequest{}
	mi := &file_internal_message_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertMessageRequest) ProtoMessage() {}

func (x *InsertMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertMessageRequest.ProtoReflect.Descriptor instead.
func (*InsertMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *InsertMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InsertMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertMessageResponse) Reset() {
	*x = InsertMessageResponse{}
	mi := &file_internal_message_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertMessageResponse) ProtoMessage() {}

func (x *InsertMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertMessageResponse.ProtoReflect.Descriptor instead.
func (*InsertMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *InsertMessageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_message_proto_message_proto protoreflect.FileDescriptor

var file_internal_message_proto_message_proto_rawDesc = []byte{
	0x0a, 0x24, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x30, 0x0a, 0x14, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x41, 0x0a, 0x15, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x60, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_message_proto_message_proto_rawDescOnce sync.Once
	file_internal_message_proto_message_proto_rawDescData = file_internal_message_proto_message_proto_rawDesc
)

func file_internal_message_proto_message_proto_rawDescGZIP() []byte {
	file_internal_message_proto_message_proto_rawDescOnce.Do(func() {
		file_internal_message_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_message_proto_message_proto_rawDescData)
	})
	return file_internal_message_proto_message_proto_rawDescData
}

var file_internal_message_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_message_proto_message_proto_goTypes = []any{
	(*InsertMessageRequest)(nil),  // 0: message.InsertMessageRequest
	(*InsertMessageResponse)(nil), // 1: message.InsertMessageResponse
}
var file_internal_message_proto_message_proto_depIdxs = []int32{
	0, // 0: message.MessageService.InsertMessage:input_type -> message.InsertMessageRequest
	1, // 1: message.MessageService.InsertMessage:output_type -> message.InsertMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_message_proto_message_proto_init() }
func file_internal_message_proto_message_proto_init() {
	if File_internal_message_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_message_proto_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_message_proto_message_proto_goTypes,
		DependencyIndexes: file_internal_message_proto_message_proto_depIdxs,
		MessageInfos:      file_internal_message_proto_message_proto_msgTypes,
	}.Build()
	File_internal_message_proto_message_proto = out.File
	file_internal_message_proto_message_proto_rawDesc = nil
	file_internal_message_proto_message_proto_goTypes = nil
	file_internal_message_proto_message_proto_depIdxs = nil
}
